apiVersion: apps/v1
kind: Deployment
metadata:
  name: logpilot-rest
  namespace: logpilot
  labels:
    app: logpilot-rest
    version: v1
    component: rest-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logpilot-rest
  template:
    metadata:
      labels:
        app: logpilot-rest
        version: v1
        component: rest-server
    spec:
      containers:
      - name: logpilot-rest
        image: logpilot-rest:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 8081
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "rest"
        - name: LOGPILOT_PROTOCOL
          value: "rest"
        - name: LOGPILOT_STORAGE_TYPE
          value: "sqlite"
        - name: LOGPILOT_SQLITE_PATH
          value: "/data/logpilot.db"
        - name: LOGPILOT_STORAGE_DIR
          value: "/data/logs"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: management
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: management
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: management
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes:
      - name: config
        configMap:
          name: logpilot-rest-config
      - name: data
        persistentVolumeClaim:
          claimName: logpilot-rest-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logpilot-rest-data
  namespace: logpilot
  labels:
    app: logpilot-rest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard