---
# ServiceAccount for Prometheus
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: logpilot
  labels:
    app: prometheus
    component: monitoring
---
# ClusterRole for Prometheus
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: monitoring
rules:
  # Access to nodes metrics
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
    verbs: ["get", "list", "watch"]

  # Access to services and endpoints
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]

  # Access to configmaps
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]

  # Access to ingresses
  - apiGroups: ["networking.k8s.io", "extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]

  # Access to ServiceMonitor and PodMonitor CRDs
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - podmonitors
      - prometheusrules
    verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for Prometheus
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: logpilot